package com.loanscrefia.admin.stats.domain;

import org.apache.ibatis.type.Alias;

import com.loanscrefia.common.common.domain.BaseDomain;

import lombok.Data;

@Data
@Alias("stats")
public class StatsDomain extends BaseDomain {

	private String plRegStat;
	private String plStat;
	private String comCodeNm;
	private String careerTypNm;
	private String codeDtlNm;
	private String plProduct;
	private String plClass;
	private String corpUserYn;
	private String name;
	private String uKey;
	
	private int case1;
	private int case2;
	private int case3;
	private int case4;
	private int case5;
	private int case6;
	private int case7;
	private int case8;
	private int case9;
	private int case10;
	private int case11;
	private int case12;
	private int case13;
	private int case14;
	private int case15;
	private int case16;
	private int case17;
	private int case18;
	private int case19;
	private int case20;
	private int case21;
	private int case22;
	private int case23;
	private int case24;
	private int case25;
	private int case26;
	private int case27;
	private int case28;
	private int case29;
	private int case30;
	private int case31;
	private int case32;
	private int case33;
	private int case34;
	private int case35;
	private int case36;
	private int case37;
	private int case38;
	private int case39;
	private int case40;
	private int case50;
	private int case51;
	private int case52;
	private int case53;
	private int case54;
	private int case55;
	private int case56;
	private int case57;
	private int case58;
	private int case59;
	private int case60;
	private int case61;
	private int case62;
	private int case63;
	private int case64;
	private int case65;
	private int case66;
	private int case67;
	private int case68;
	private int case69;
	private int case70;
	private int case71;
	private int case72;
	private int case73;
	private int case74;
	private int case75;
	private int case76;
	private int case77;
	private int case78;
	private int case79;
	private int case80;
	private int case81;
	private int case82;
	private int case83;
	private int case84;
	private int case85;
	private int case86;
	private int case87;
	private int case88;
	
	private int total1;
	private int total2;
	private int total3;
	private int total4;
	private int total5;
	private int total6;
	private int total7;
	private int total8;
	private int total9;
	private int total10;
	private int total11;
	private int total12;
	private int total13;
	private int total14;
	private int total15;
	private int total16;
	private int total17;
	private int total18;
	private int total19;
	private int total20;
	private int total21;
	private int total22;
	private int total23;
	private int total24;
	private int total25;
	private int total26;
	private int total27;
	private int total28;
	private int total29;
	private int total30;
	private int total31;
	private int total32;
	private int total33;
	private int total34;
	private int total35;
	private int total36;
	private int total37;
	private int total38;
	private int total39;
	private int total40;
	private int total41;
	private int total42;
	private int total43;
	private int total44;
	
}
