server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      cookie:
        name: K_IDF2
        http-only: true
  tomcat:
    max-swallow-size: 1
        

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

---
spring:
  profiles: local
  mst:
    datasource:
      hikari:
        pool-name: MASTER-DB
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:postgresql://pg1101.gabiadb.com:5432/loans
        username: loanadmin
        password: qwer1234!@
        maximum-pool-size: 1
  email:
    datasource:
      hikari:
        pool-name: EMAIL-DB
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    
  sms:
    datasource:
      hikari:
        pool-name: SMS-DB
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    
logging:
  file:
    path: C:\logs\
    max-history: 1
    max-size:
      8MB
  level:
    org.springframework: debug
    worg.hibernate.type: debug
    jdbc.audit: off
    jdbc.connection: off
    jdbc.resultset: off
    jdbc.sqlonly: debug

upload:
  filePath: C:\Users\a\git\loans\src\main\resources\static\upload
  
download:
  filePath: C:\Users\a\git\loans\src\main\resources\static\upload

kfbApi:
  url: http://172.16.123.10:43003
  apply: false
 
crypto:
  apply: false
 
email:
  apply: false
  
sms:
  apply: false
  
---




spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
  mst:
    datasource:
      hikari:
        pool-name: MASTER-DB
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:postgresql://192.168.170.102:5432/postgres
        username: postgres
        password: 1234
        
  email:
    datasource:
      hikari:
        pool-name: EMAIL-DB
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://112.175.78.211:1433;databaseName=CEWEB
    username: cemms
    password: cemms1234
    
  sms:
    datasource:
      hikari:
        pool-name: SMS-DB
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://112.175.78.211:1433;DatabaseName=CESMS
    username: cesms
    password: cesms001

        
logging:
  file:
    path: C:\logs\
    max-history: 1
    max-size:
      8MB
  level:
    org.springframework: error
    #worg.hibernate.type: info
    jdbc.audit: off
    jdbc.connection: off
    jdbc.resultset: off
    jdbc.sqlonly: error
   
   
   
upload:
  filePath: Z:\loanscrefia\static\upload
  
download:
  filePath: Z:\loanscrefia\static\upload
    
kfbApi:
  url: http://172.16.123.10:43003
  apply: true
  
crypto:
  apply: true
  
email:
  apply: true
  
sms:
  apply: true
  
  
---

spring:
  profiles: prod
  devtools:
    restart:
      enabled: true
  mst:
    datasource:
      hikari:
        pool-name: MASTER-DB
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:postgresql://192.168.170.103:5432/postgres
        username: postgres
        password: crefiaL0ans!@
        
        
  email:
    datasource:
      hikari:
        pool-name: EMAIL-DB
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://112.175.78.211:1433;databaseName=CEWEB
    username: cemms
    password: cemms1234
    
  sms:
    datasource:
      hikari:
        pool-name: SMS-DB
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://112.175.78.211:1433;DatabaseName=CESMS
    username: cesms
    password: cesms001

        
logging:
  file:
    path: C:\logs\
    max-history: 1
    max-size:
      8MB
  level:
    org.springframework: error
    #worg.hibernate.type: info
    jdbc.audit: off
    jdbc.connection: off
    jdbc.resultset: off
    jdbc.sqlonly: error
   
   
   
upload:
  filePath: Z:\loanscrefia\static\upload
  
download:
  filePath: Z:\loanscrefia\static\upload
  

kfbApi:
  url: http://172.16.33.10:33003
  apply: true

crypto:
  apply: true
  
email:
  apply: true
  
sms:
  apply: true
  
  