server:
  port: 8080
  servlet:
    session:
      cookie:
        name: K_IDF 
        http-only: true
        

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

---
spring:
  profiles: local
  mst:
    datasource:
      hikari:
        pool-name: MASTER-DB
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 1234
  read:
    datasource:
      hikari:
        pool-name: READ-DB
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

logging:
  level:
    #org.springframework: error
    #worg.hibernate.type: info
    jdbc.audit: off
    jdbc.connection: off
    jdbc.resultset: off
    jdbc.sqlonly: error


upload:
  filePath: C:\Users\a\git\loans\src\main\resources\static\upload
  
download:
  filePath: C:\Users\a\git\loans\src\main\resources\static\upload

#upload:
#  filePath: static\upload
  
---




spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
  mst:
    datasource:
      hikari:
        pool-name: MASTER-DB
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:postgresql://192.168.170.102:5432/postgres
        username: postgres
        password: 1234
  read:
    datasource:
      hikari:
        pool-name: READ-DB
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://112.175.78.211:1433/CEWEB
    username: cemms
    password: cemms1234
      
logging:
  level:
    org.springframework: debug
    jdbc.audit: off
    jdbc.connection: off
    jdbc.resultset: off
    jdbc.sqlonly: error
   
   
   
upload:
  filePath: Z:\loanscrefia\static\upload
  
download:
  filePath: Z:\loanscrefia\static\upload
    
---

spring:
  profiles: prd
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    
logging:
  level:
    org.springframework: error
  
