server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      cookie:
        name: K_IDF2
        http-only: true
  tomcat:
    max-swallow-size: 1
        

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

---
spring:
  profiles: local
  datasource:
    hikari:
      mst:
        pool-name: MASTER-DB
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:postgresql://lcj0821.synology.me:543/postgres
        username: admin
        password: admin
        maximum-pool-size: 1
      email:
        pool-name: EMAIL-DB
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:postgresql://lcj0821.synology.me:543/postgres
        username: admin
        password: admin
        maximum-pool-size: 1
      sms:
        pool-name: SMS-DB
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:postgresql://lcj0821.synology.me:543/postgres
        username: admin
        password: admin
        maximum-pool-size: 1
logging:
  file:
    path: C:\logs\
    max-history: 1
    max-size:
      8MB
  level:
    org.springframework: error
    #com.zaxxer.hikari.HikariConfig: TRACE
    #com.zaxxer.hikari: TRACE
    log4jdbc.log4j2: info
    jdbc.audit: off
    jdbc.connection: off
    jdbc.resultset: off
    jdbc.sqlonly: debug

upload:
  filePath: C:\Users\a\git\loans\src\main\resources\static\upload
  
download:
  filePath: C:\Users\a\git\loans\src\main\resources\static\upload

kfbApi:
  url: http://172.16.123.10:43003
  apply: false
 
crypto:
  apply: false
 
email:
  apply: false
  
sms:
  apply: false
  
---


spring:
  profiles: dev
  datasource:
    hikari:
      mst:
        pool-name: MASTER-DB
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:postgresql://192.168.170.102:5432/postgres
        username: postgres
        password: 1234
      email:
        pool-name: EMAIL-DB
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        jdbc-url: jdbc:sqlserver://112.175.78.211:1433;databaseName=CEWEB
        username: cemms
        password: cemms1234
      sms:
        pool-name: SMS-DB
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        jdbc-url: jdbc:sqlserver://112.175.78.211:1433;DatabaseName=CESMS
        username: cesms
        password: cesms001
        
logging:
  file:
    path: C:\logs\
    max-history: 1
    max-size:
      8MB
  level:
    org.springframework: error
    #worg.hibernate.type: info
    jdbc.audit: off
    jdbc.connection: off
    jdbc.resultset: off
    jdbc.sqlonly: error
   
   
   
upload:
  filePath: Z:\loanscrefia\static\upload
  
download:
  filePath: Z:\loanscrefia\static\upload
    
kfbApi:
  url: http://172.16.123.10:43003
  apply: true
  
crypto:
  apply: true
  
email:
  apply: true
  
sms:
  apply: true
  
api:
  key:
    juso: devU01TX0FVVEgyMDIxMDkxMDEwNTk1MjExMTY1MDE=

enc:
  key:
    location: Z:\loanscrefia\libs\Private2048.key.der

time:
  vaild:
    pwdToken: true
  lock:
    inactive: true

cert:
  siteUrl: http://loanagentd.crefia.or.kr/
  cpCd: V40830000001
  key:
    location: Z:\loanscrefia\libs\V40830000001_IDS_01_PROD_AES_license.dat
    
  
---

spring:
  profiles: prod
  datasource:
    hikari:
      mst:
        pool-name: MASTER-DB
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:postgresql://192.168.170.103:5432/postgres
        username: postgres
        password: crefiaL0ans!@
      email:
        pool-name: EMAIL-DB
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        jdbc-url: jdbc:sqlserver://112.175.78.211:1433;databaseName=CEWEB
        username: cemms
        password: cemms1234
      sms:
        pool-name: SMS-DB
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        jdbc-url: jdbc:sqlserver://112.175.78.211:1433;DatabaseName=CESMS
        username: cesms
        password: cesms001
        
logging:
  file:
    path: C:\logs\
    max-history: 1
    max-size:
      8MB
  level:
    org.springframework: error
    #worg.hibernate.type: info
    jdbc.audit: off
    jdbc.connection: off
    jdbc.resultset: off
    jdbc.sqlonly: error
   
   
   
upload:
  filePath: Z:\loanscrefia\static\upload
  
download:
  filePath: Z:\loanscrefia\static\upload
  

kfbApi:
  url: http://172.16.33.10:33003
  apply: true

crypto:
  apply: true
  
email:
  apply: true
  
sms:
  apply: true
  
  